print("Введіть значення числа A")
a=int(input())
print("Введіть значення числа B")
b=int(input())
print("Введіть значення числа C")
c=int(input())
print("Введіть значення числа D")
d=int(input())
print(a + b// c**d)